import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="bg-[#0d1525] sticky top-0 z-20 w-full px-6 py-4 font-bold text-lg gap-x-3 flex flex-row">
        <div className="basis-full">NFTSITE</div>
        <div>Search</div>
        <div>Menu</div>
      </header>

      <div className="fixed left-0 right-0 top-0 bottom-0 bg-gradient-to-b from-slate-900 to-black">
      </div>
      
      <main className="px-6 flex flex-col gap-y-16 z-10">

        <h1 className="font-bold text-4xl py-8 z-10">
          <div className="drop-shadow-[0_1px_1px_rgba(0,0,0,1)]">Explore and discover NFTs across the top marketplaces</div>
        </h1>

        <h2 className="font-semibold text-lg z-10">
          Trending collections
          <div className="border-white border rounded-md w-full h-64 animate-pulse bg-neutral-400 z-10">
          </div>
        </h2>
        
        <div className="rounded-md bg-yellow-500 p-2 text-black w-10/12 self-center z-10">
          <div className="flex items-center justify-center">Explore all collections</div>
        </div>

        <div className="bg-yellow-500 pb-4 rounded-md z-10">
          <div className="font-semibold flex justify-center items-center pt-2 pb-4">Join the community</div>
          <div className="flex flex-row justify-evenly">
            <div className="p-4 rounded-md bg-purple-400">Discord</div>
            <div className="p-4 rounded-md bg-blue-500">Twitter</div>
            <div className="p-4 rounded-md bg-orange-500">Reddit</div>
          </div>
        </div>

        <div className="grid grid-cols-4 justify-items-center gap-y-4 z-10">
          <div>About</div>
          <div>API</div>
          <div>Contact</div>
          <div>Careers</div>
          <div>Docs</div>
          <div>Help</div>
          <div>Newsletter</div>
          <div>Terms</div>
        </div>


          <div className="border-t-[1px] flex flex-col py-4 justify-center items-center z-10">
            <div>NFTSITE - 2022</div>
            <div>An @uncoolzero industries product</div>
          </div>
      </main>

    </div>
  )
}
